export const icons = {
  githubIcon: 'assets/icons/github.png',
  cssIcon: 'assets/icons/css.png',
  downloadingIcon: 'assets/icons/downloading.png',
  globeIcon: 'assets/icons/globe.png',
  htmlIcon: 'assets/icons/html.png',
  jsIcon: 'assets/icons/js.png',
  reactIcon: 'assets/icons/react.png',
  linkedinIcon: 'assets/icons/linkedin.png',
  typescriptIcon: 'assets/icons/typescript.png',
  userIcon: 'assets/icons/user.png',
  sendIcon: 'assets/icons/enviar.png',
  emailIcon: 'assets/icons/email.png',
  chatIcon: 'assets/icons/chat.png',
  instagramIcon: 'assets/icons/instagram.png',
  bootstrapIcon: 'assets/icons/bootstrap.png',
  firebaseIcon: 'assets/icons/firebase.png',
  gitIcon: 'assets/icons/git.png',
  nodejsIcon: 'assets/icons/nodejs.png',
  sassIcon: 'assets/icons/sass.png',
  sqlIcon: 'assets/icons/sql.png',
  supabaseIcon: 'assets/icons/supabase.png',
}
