export const icons = {
  githubIcon: 'assets/icons/github.png',
  css3Icon: 'assets/icons/css.png',
  downloadingIcon: 'assets/icons/downloading.png',
  globeIcon: 'assets/icons/globe.png',
  htmlIcon: 'assets/icons/html.png',
  jsIcon: 'assets/icons/js.png',
  reactIcon: 'assets/icons/react.png',
  linkedinIcon: 'assets/icons/linkedin.png',
  typescriptIcon: 'assets/icons/typescript.png',
  userIcon: 'assets/icons/user.png',
  sendIcon: 'assets/icons/enviar.png',
  emailIcon: 'assets/icons/email.png',
  chatIcon: 'assets/icons/chat.png',
  instagramIcon: 'assets/icons/instagram.png',
}
